### ISSUE TITLE
(1) Acquisition Phase: We do not have a pneumatically actuated Ethanol Valve 

### ISSUE THREAD

**Issue by KyleMeeuwsen** [psas/liquid-engine-test-stand#11]
This valve needs to be pneumatically actuated with at least an 3/8" inlet and outlet diameter. 

Swagelok potentially has the ability to provide this valve with a pneumatic actuator as a package. **This actuator needs to have an open/close time of less than 4 seconds (preferably around 2 seconds).

**Comment by matthewhauer** [comment]
Has a particular part number/piece, or a set of viable pieces, been identified?  Is this a part selection or procurement issue?
