### ISSUE TITLE
(2) Build Phase: CAD Layout

### ISSUE THREAD

**Issue by matthewhauer** [psas/liquid-engine-test-stand#12]
Tyler, Kyle.

Construct a CAD drawing with simplified models of the parts to lay out the structure of the test stand and how they fit together.  Make sure the human-accessible parts are all together.

Simple primitive solids are suitable for this task at this point.

This ticket shall be accepted when a  3D diagram has been posted to the GitHub account.

**Comment by KyleMeeuwsen** [comment]
Asa, I have been unsuccessful at moving the adobe file to github. For some reason Github will not take the adobe file. I have not tried the solidworks file and will attempt this either tonight or possibly tomorrow.

**Comment by asa-grant** [comment]
Thanks man. Thanks for doing this for me, I need to sit down with github for an hour or so and just familiarize myself with it that way I can do it on my own.

-Asa

On Jul 26, 2016, at 11:01 PM, Kyle Meeuwsen <notifications@github.com<mailto:notifications@github.com>> wrote:

Asa, I have been unsuccessful at moving the adobe file to github. For some reason Github will not take the adobe file. I have not tried the solidworks file and will attempt this either tonight or possibly tomorrow.

**Comment by 7deeptide** [comment]
Guys, please let me know if you'd ever like a sit-down git tutorial from me... I'd be happy to do it at the next propulsion meeting if you like (you'll just need to bring your laptops).

**Comment by asa-grant** [comment]
That would awesome!

Thanks!

-Asa

On Jul 27, 2016, at 3:02 PM, Erin <notifications@github.com<mailto:notifications@github.com>> wrote:

Guys, please let me know if you'd ever like a sit-down git tutorial from me... I'd be happy to do it at the next propulsion meeting if you like (you'll just need to bring your laptops).
