### ISSUE TITLE
(3) Test Preparation Phase: Create safety and handling proceedures for LFETS

### ISSUE THREAD

**Issue by matthewhauer** [psas/liquid-engine-test-stand#15]
As title.

Accepted when there's a committed procedure handbook.

**Comment by matthewhauer** [comment]
We don't want to blow anything up or kill off the interns.  So write up how not to lose body parts.

**Comment by matthewhauer** [comment]
Very related to #16 ... may be duplicate, but @KyleMeeuwsen  is certainly more creative in his descriptions than I am.

**Comment by MechBertrand** [comment]
See https://github.com/psas/liquid-engine-test-stand/issues/16
