### ISSUE TITLE
Test Preparation Phase: Build Standard Operating Procedures (SOP) and Operators Handbook

### ISSUE THREAD

**Issue by KyleMeeuwsen** [psas/liquid-engine-test-stand#16]
Examples: Do not place N2 tanks in the back seat of a car with closed windows. If N2 leaks, individuals in the car my asphyxiate.

**Comment by KyleMeeuwsen** [comment]
See manual (template) for launch and apply it to test stand. Ensure compliance with ASME, Cryo handling, Boiler Code, etc. Erin to comment more on this.

**Comment by MechBertrand** [comment]
Marked similar topics as duplicate. Renames this issue as SOP:... from "Need a safety manual for the transportation, handling, and installation of all materials and fluids."

Link to standardized procedure book: https://github.com/psas/procedure-book

Will soon be creating an LFETS SOP and Operators' Hanbook starting with a copy of this link.

**Comment by MechBertrand** [comment]
Closed Duplicates:
https://github.com/psas/liquid-engine-test-stand/issues/13
https://github.com/psas/liquid-engine-test-stand/issues/15
