### ISSUE TITLE
(1) Acquisition Phase: Determine appropriate valve actuation times

### ISSUE THREAD

**Issue by matthewhauer** [psas/liquid-engine-test-stand#17]
Ask Bob and ARocket about reasonable times for ball valve actuator for the ethanol and LOX main valves.  We don't want to screw up the combustion chamber with questionably timed LOX and ethanol flow.

This ticket shall be accepted when ...

**Comment by KyleMeeuwsen** [comment]
The two second open time on the LOX actuator is acceptable since based on Gregory and Robert's feedback as long as the valve is a ball valve. The ball valve allows us to crack the valve open, allowing a small amount of LOX to flow through the system, eliminating the two phase flow.

**Comment by KyleMeeuwsen** [comment]
Selected 3/8" brass ball valve with 6.4 Cv. 

Part Number: B-6P6T from Swagelok with Ferrule fittings.
