### ISSUE TITLE
(1) Acquisition Phase: FEA Analysis and Sizing of Load Cells

### ISSUE THREAD

**Issue by DylanStephens** [psas/liquid-engine-test-stand#24]
There will be four load cells measuring the engine's thrust. The design's measurements are in English units. The force should be applied to the bottom face of the hole that is above the relief cut. The file that needs to be analyzed can be found here: https://github.com/psas/liquid-engine-test-stand/tree/master/SW%20CAD/Test%20Stand%20Assembly Labeled as Loadcell7. The load cell needs to be analyzed for the maximum stress without yielding.

**Comment by KyleMeeuwsen** [comment]
After solving, send results to Dylan and discuss iterative analysis approach.

**Comment by KyleMeeuwsen** [comment]
Later- Temperature concerns to be addressed later. 
May necessitate a protective casing for environment isolation and thermocouples and possibly LOX lines for cooling around casing?
