### ISSUE TITLE
Add GOX and Ethanol igniter solenoids

### ISSUE THREAD

**Issue by 7deeptide** [psas/liquid-engine-test-stand#31]
The Gems A2012-2M-OC-V-VO-C204 (500 psi, 3/64 inch opening, Cv=0.035) vale was suggested by Robert Watzlavick. Thesse should work for both the GOX and IPA taps. [link](http://www.gemssensors.com/Solenoid-Valves/General-Purpose/A-Series-Solenoid-Valve)

**Comment by KyleMeeuwsen** [comment]
Line size from the union cross on the LOX side to the ignitor is 1/8" with an AN flare.  The ignitor will receive both Ethanol and LOX. 

Need to get flow rates from Kyle Blakemen.

**Comment by asa-grant** [comment]
We wouldn't do a 1/8" union cross. We need 1/2" union crosses and then 1/2" to 1/8" tube adapters FYI.

On Oct 4, 2016, at 6:16 PM, Kyle Meeuwsen <notifications@github.com<mailto:notifications@github.com>> wrote:

Line size from the union cross on the LOX side to the ignitor is 1/8" with an AN flare. The ignitor will receive both Ethanol and LOX.

Need to get flow rates from Kyle Blakemen.
