### ISSUE TITLE
Isopropyl Alcohol Sources and Storage

### ISSUE THREAD

**Issue by MechBertrand** [psas/liquid-engine-test-stand#38]
**Issue:** Isopropyl Alcohol Sources and Storage

**Description:** We need to identify suppliers and storage options for our fuel!

**Objective/Goal:** Identify Storage options, distributors of IPA, and whether we want pre-diluted or 99% bulk.

**Background:** 

Our engine runs on 70% Ethanol. Since this is a stable product that can be stored for long periods at room temperature, it may be ordered at any time.

One distributor - [Pemro](http://www.pemro.com/Results.cfm?category=IPA&gclid=CMGG3dHpwNQCFRKUfgodp9kJ1w)

**Deliverable:** 

- [ ]  Storage location and procedures Identified and reserved
- [ ]  Decision made between factory diluted (70%) or dilution in-house (99%)
- [ ]  Short list of suppliers identified and consolidated
- [ ]  Quantity to order at a time (Quantity versus price)

**Comment by 7deeptide** [comment]
@MechBertrand It's also an option to buy higher concentrations that 70% abv and dilute it ourselves.
