### ISSUE TITLE
Main Fuel Valve

### ISSUE THREAD

**Issue by JacobTiller** [psas/liquid-engine-test-stand#41]
**Project** : Design and build electrically actuated main fuel valve

**Description** : The final valve connecting the pressurized fuel line to the test engine needs to be activated and controlled remotely.  This project is to design and build a servo / motor driven valve which is capable of opening the main fuel valve.

**Requirements** : 

The valve which has been selected for use as the main fuel valve is a Sharpe 39036 1/2 in ball valve.  (see doc file for specification sheet). 

** constraints:**
  - Opening torque for ball valve - 35 in.lb's per manufacturer
 - Power supply - 12V DC or less
 - For testing, the hardware should be able to be run with an Arduino

**Deliverable:** The valve needs to be able to be reliably opened and closed.  Will need to be able to withstand strenuous testing.

**Comment by MechBertrand** [comment]
initial wOrk done on the DC motor. Check out the readme to see how to NOT make a valve work XD
