### ISSUE TITLE
(2) Build Phase: Specify LFETS/LTC command packets

### ISSUE THREAD

**Issue by matthewhauer** [psas/liquid-engine-test-stand#9]
The LFETS will have both a 'direct' (plug in to Marionette DAQ via USB) and 'telemetered' configuration.  In the latter, a psas_packet type shall be used to send command message to the LFETS.

The contents of these command messages needs to be specified.  In doing so, the available actions on the test stand shall specify the options, and be documented.

This ticket shall be accepted when a psas_packet 'LFETS command' type has been written up.  A follow-up ticket shall be to implement said type.

**Comment by matthewhauer** [comment]
Tagging @jameysharp as psas_packet SME.

**Comment by matthewhauer** [comment]
Lean on @KyleMeeuwsen about the list of test stand commands required for the command packets.  IE, the individual commands to define in the packet spec.

**Comment by jameysharp** [comment]
Sorry I never got to this, but I'm not sure what I was expected to do. If you're still interested, can we talk about it at a regular Tuesday evening meeting?
